# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'companyPlacementStatistics.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCharts import QChartView
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QMainWindow,
    QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1920, 1060)
        MainWindow.setMinimumSize(QSize(1920, 1060))
        MainWindow.setMaximumSize(QSize(1920, 1060))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"#centralwidget {\n"
"	background-image: url(:/icons/studentStatbg.png);\n"
"}\n"
"")
        self.LOGO = QLabel(self.centralwidget)
        self.LOGO.setObjectName(u"LOGO")
        self.LOGO.setGeometry(QRect(100, 0, 258, 165))
        self.LOGO.setStyleSheet(u"")
        self.LOGO.setPixmap(QPixmap(u":/icons/applogo.png"))
        self.lineGraphView = QChartView(self.centralwidget)
        self.lineGraphView.setObjectName(u"lineGraphView")
        self.lineGraphView.setGeometry(QRect(40, 140, 751, 421))
        self.lineGraphView.setStyleSheet(u"border-radius:10px;")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(890, 140, 381, 101))
        self.widget.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"")
        self.totalCompaniesText = QLabel(self.widget)
        self.totalCompaniesText.setObjectName(u"totalCompaniesText")
        self.totalCompaniesText.setGeometry(QRect(120, 50, 241, 31))
        font = QFont()
        font.setFamilies([u"Lucida Sans"])
        font.setPointSize(18)
        font.setBold(True)
        self.totalCompaniesText.setFont(font)
        self.totalCompaniesLabel = QLabel(self.widget)
        self.totalCompaniesLabel.setObjectName(u"totalCompaniesLabel")
        self.totalCompaniesLabel.setGeometry(QRect(120, 20, 51, 31))
        self.totalCompaniesLabel.setFont(font)
        self.label_19 = QLabel(self.widget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(40, 20, 60, 60))
        self.label_19.setStyleSheet(u"")
        self.label_19.setPixmap(QPixmap(u":/icons/totalCompanyImg.png"))
        self.pieChartView = QChartView(self.centralwidget)
        self.pieChartView.setObjectName(u"pieChartView")
        self.pieChartView.setGeometry(QRect(1370, 140, 501, 421))
        self.pieChartView.setStyleSheet(u"border-radius:10px;")
        self.widget_4 = QWidget(self.centralwidget)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setGeometry(QRect(1370, 630, 501, 331))
        self.widget_4.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"")
        self.companiesNotVisitedText = QLabel(self.widget_4)
        self.companiesNotVisitedText.setObjectName(u"companiesNotVisitedText")
        self.companiesNotVisitedText.setGeometry(QRect(140, 90, 311, 31))
        self.companiesNotVisitedText.setFont(font)
        self.companiesNotVisitedLabel = QLabel(self.widget_4)
        self.companiesNotVisitedLabel.setObjectName(u"companiesNotVisitedLabel")
        self.companiesNotVisitedLabel.setGeometry(QRect(140, 60, 51, 31))
        self.companiesNotVisitedLabel.setFont(font)
        self.companiesNotHiredtext = QLabel(self.widget_4)
        self.companiesNotHiredtext.setObjectName(u"companiesNotHiredtext")
        self.companiesNotHiredtext.setGeometry(QRect(140, 250, 311, 31))
        self.companiesNotHiredtext.setFont(font)
        self.companiesNotHiredLabel = QLabel(self.widget_4)
        self.companiesNotHiredLabel.setObjectName(u"companiesNotHiredLabel")
        self.companiesNotHiredLabel.setGeometry(QRect(140, 220, 51, 31))
        self.companiesNotHiredLabel.setFont(font)
        self.label_17 = QLabel(self.widget_4)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(50, 60, 60, 60))
        self.label_17.setStyleSheet(u"")
        self.label_17.setPixmap(QPixmap(u":/icons/companiesDidNotVistImg.png"))
        self.label_18 = QLabel(self.widget_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(50, 220, 60, 60))
        self.label_18.setStyleSheet(u"")
        self.label_18.setPixmap(QPixmap(u":/icons/companiesDidNotHireImg.png"))
        self.barGraphView = QChartView(self.centralwidget)
        self.barGraphView.setObjectName(u"barGraphView")
        self.barGraphView.setGeometry(QRect(40, 630, 1231, 331))
        self.barGraphView.setStyleSheet(u"border-radius:10px;")
        self.batchComboBox = QComboBox(self.centralwidget)
        self.batchComboBox.addItem("")
        self.batchComboBox.addItem("")
        self.batchComboBox.addItem("")
        self.batchComboBox.setObjectName(u"batchComboBox")
        self.batchComboBox.setGeometry(QRect(470, 50, 201, 31))
        self.batchComboBox.setEditable(False)
        self.typeOfJobCombobox = QComboBox(self.centralwidget)
        self.typeOfJobCombobox.addItem("")
        self.typeOfJobCombobox.addItem("")
        self.typeOfJobCombobox.addItem("")
        self.typeOfJobCombobox.setObjectName(u"typeOfJobCombobox")
        self.typeOfJobCombobox.setGeometry(QRect(770, 50, 201, 31))
        self.ctcCombobox = QComboBox(self.centralwidget)
        self.ctcCombobox.addItem("")
        self.ctcCombobox.addItem("")
        self.ctcCombobox.addItem("")
        self.ctcCombobox.addItem("")
        self.ctcCombobox.addItem("")
        self.ctcCombobox.addItem("")
        self.ctcCombobox.addItem("")
        self.ctcCombobox.addItem("")
        self.ctcCombobox.addItem("")
        self.ctcCombobox.setObjectName(u"ctcCombobox")
        self.ctcCombobox.setGeometry(QRect(1070, 50, 201, 31))
        self.levelOfJobCombobox = QComboBox(self.centralwidget)
        self.levelOfJobCombobox.addItem("")
        self.levelOfJobCombobox.addItem("")
        self.levelOfJobCombobox.addItem("")
        self.levelOfJobCombobox.addItem("")
        self.levelOfJobCombobox.addItem("")
        self.levelOfJobCombobox.addItem("")
        self.levelOfJobCombobox.addItem("")
        self.levelOfJobCombobox.addItem("")
        self.levelOfJobCombobox.addItem("")
        self.levelOfJobCombobox.addItem("")
        self.levelOfJobCombobox.setObjectName(u"levelOfJobCombobox")
        self.levelOfJobCombobox.setGeometry(QRect(1370, 50, 201, 31))
        self.sectorCombobox = QComboBox(self.centralwidget)
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.addItem("")
        self.sectorCombobox.setObjectName(u"sectorCombobox")
        self.sectorCombobox.setGeometry(QRect(1670, 50, 201, 31))
        self.widget_2 = QWidget(self.centralwidget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(890, 460, 381, 101))
        self.widget_2.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"")
        self.companiesHiredText = QLabel(self.widget_2)
        self.companiesHiredText.setObjectName(u"companiesHiredText")
        self.companiesHiredText.setGeometry(QRect(120, 50, 241, 31))
        self.companiesHiredText.setFont(font)
        self.companiesHiredLabel = QLabel(self.widget_2)
        self.companiesHiredLabel.setObjectName(u"companiesHiredLabel")
        self.companiesHiredLabel.setGeometry(QRect(120, 20, 51, 31))
        self.companiesHiredLabel.setFont(font)
        self.label_21 = QLabel(self.widget_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(40, 20, 60, 60))
        self.label_21.setStyleSheet(u"")
        self.label_21.setPixmap(QPixmap(u":/icons/companiesHiredImg.png"))
        self.widget_3 = QWidget(self.centralwidget)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(890, 300, 381, 101))
        self.widget_3.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"")
        self.companiesVisitedText = QLabel(self.widget_3)
        self.companiesVisitedText.setObjectName(u"companiesVisitedText")
        self.companiesVisitedText.setGeometry(QRect(120, 50, 241, 31))
        self.companiesVisitedText.setFont(font)
        self.companiesVisitedLabel = QLabel(self.widget_3)
        self.companiesVisitedLabel.setObjectName(u"companiesVisitedLabel")
        self.companiesVisitedLabel.setGeometry(QRect(120, 20, 51, 31))
        self.companiesVisitedLabel.setFont(font)
        self.label_20 = QLabel(self.widget_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(40, 20, 60, 60))
        self.label_20.setStyleSheet(u"")
        self.label_20.setPixmap(QPixmap(u":/icons/companiesVisitedImg.png"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.LOGO.setText("")
        self.totalCompaniesText.setText(QCoreApplication.translate("MainWindow", u"Total Companies", None))
        self.totalCompaniesLabel.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.label_19.setText("")
        self.companiesNotVisitedText.setText(QCoreApplication.translate("MainWindow", u"Companies Did Not Visit", None))
        self.companiesNotVisitedLabel.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.companiesNotHiredtext.setText(QCoreApplication.translate("MainWindow", u"Companies Did Not Hire", None))
        self.companiesNotHiredLabel.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.label_17.setText("")
        self.label_18.setText("")
        self.batchComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"2024", None))
        self.batchComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"2023", None))
        self.batchComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"2022", None))

        self.typeOfJobCombobox.setItemText(0, QCoreApplication.translate("MainWindow", u"All", None))
        self.typeOfJobCombobox.setItemText(1, QCoreApplication.translate("MainWindow", u"FULL TIME", None))
        self.typeOfJobCombobox.setItemText(2, QCoreApplication.translate("MainWindow", u"INTERNSHIP", None))

        self.ctcCombobox.setItemText(0, QCoreApplication.translate("MainWindow", u"All", None))
        self.ctcCombobox.setItemText(1, QCoreApplication.translate("MainWindow", u"2LPA-5LPA", None))
        self.ctcCombobox.setItemText(2, QCoreApplication.translate("MainWindow", u"5LPA-10LPA", None))
        self.ctcCombobox.setItemText(3, QCoreApplication.translate("MainWindow", u"10LPA-15LPA", None))
        self.ctcCombobox.setItemText(4, QCoreApplication.translate("MainWindow", u"15LPA-20LPA", None))
        self.ctcCombobox.setItemText(5, QCoreApplication.translate("MainWindow", u"20LPA-25LPA", None))
        self.ctcCombobox.setItemText(6, QCoreApplication.translate("MainWindow", u"25LPA-30LPA", None))
        self.ctcCombobox.setItemText(7, QCoreApplication.translate("MainWindow", u"30LPA-35LPA", None))
        self.ctcCombobox.setItemText(8, QCoreApplication.translate("MainWindow", u"35LPA-40LPA", None))

        self.levelOfJobCombobox.setItemText(0, QCoreApplication.translate("MainWindow", u"All", None))
        self.levelOfJobCombobox.setItemText(1, QCoreApplication.translate("MainWindow", u"Level 1 - Dream", None))
        self.levelOfJobCombobox.setItemText(2, QCoreApplication.translate("MainWindow", u"Level 1 - General", None))
        self.levelOfJobCombobox.setItemText(3, QCoreApplication.translate("MainWindow", u"Level 1 - BPO", None))
        self.levelOfJobCombobox.setItemText(4, QCoreApplication.translate("MainWindow", u"Level 2 - Dream", None))
        self.levelOfJobCombobox.setItemText(5, QCoreApplication.translate("MainWindow", u"Level 2 - General", None))
        self.levelOfJobCombobox.setItemText(6, QCoreApplication.translate("MainWindow", u"Level 2 - BPO", None))
        self.levelOfJobCombobox.setItemText(7, QCoreApplication.translate("MainWindow", u"Level 3 - Dream", None))
        self.levelOfJobCombobox.setItemText(8, QCoreApplication.translate("MainWindow", u"Level 3 - General", None))
        self.levelOfJobCombobox.setItemText(9, QCoreApplication.translate("MainWindow", u"Level 3 - BPO", None))

        self.sectorCombobox.setItemText(0, QCoreApplication.translate("MainWindow", u"All", None))
        self.sectorCombobox.setItemText(1, QCoreApplication.translate("MainWindow", u"ACTUARY", None))
        self.sectorCombobox.setItemText(2, QCoreApplication.translate("MainWindow", u"ADVERTISING MEDIA PR", None))
        self.sectorCombobox.setItemText(3, QCoreApplication.translate("MainWindow", u"BANKING AND FINANCIAL SERVICES", None))
        self.sectorCombobox.setItemText(4, QCoreApplication.translate("MainWindow", u"BUSINESS DEVELOPMENT", None))
        self.sectorCombobox.setItemText(5, QCoreApplication.translate("MainWindow", u"CONSULTING", None))
        self.sectorCombobox.setItemText(6, QCoreApplication.translate("MainWindow", u"CUSTOMER TECHNICAL SUPPORT", None))
        self.sectorCombobox.setItemText(7, QCoreApplication.translate("MainWindow", u"DATA ANALYTICS", None))
        self.sectorCombobox.setItemText(8, QCoreApplication.translate("MainWindow", u"DESIGN ART", None))
        self.sectorCombobox.setItemText(9, QCoreApplication.translate("MainWindow", u"ENGINEERING", None))
        self.sectorCombobox.setItemText(10, QCoreApplication.translate("MainWindow", u"ENGINEERING CORE", None))
        self.sectorCombobox.setItemText(11, QCoreApplication.translate("MainWindow", u"ENGINEERING WEB SOFTWARE", None))
        self.sectorCombobox.setItemText(12, QCoreApplication.translate("MainWindow", u"EDUCATION TEACHING TRAINING", None))
        self.sectorCombobox.setItemText(13, QCoreApplication.translate("MainWindow", u"FINANCE", None))
        self.sectorCombobox.setItemText(14, QCoreApplication.translate("MainWindow", u"INFORMATION TECHNOLOGY", None))
        self.sectorCombobox.setItemText(15, QCoreApplication.translate("MainWindow", u"GENERAL MANAGEMENT", None))
        self.sectorCombobox.setItemText(16, QCoreApplication.translate("MainWindow", u"HUMAN RESOURCES", None))
        self.sectorCombobox.setItemText(17, QCoreApplication.translate("MainWindow", u"OPERATIONS PRODUCTION", None))
        self.sectorCombobox.setItemText(18, QCoreApplication.translate("MainWindow", u"PROJECT MANAGEMENT", None))
        self.sectorCombobox.setItemText(19, QCoreApplication.translate("MainWindow", u"QUALITY ASSURANCE", None))
        self.sectorCombobox.setItemText(20, QCoreApplication.translate("MainWindow", u"SALES", None))
        self.sectorCombobox.setItemText(21, QCoreApplication.translate("MainWindow", u"WRITING EDITING", None))

        self.companiesHiredText.setText(QCoreApplication.translate("MainWindow", u"Companies Hired", None))
        self.companiesHiredLabel.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.label_21.setText("")
        self.companiesVisitedText.setText(QCoreApplication.translate("MainWindow", u"Companies Visited", None))
        self.companiesVisitedLabel.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.label_20.setText("")
    # retranslateUi

